VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IReportingHandler_AgencyFuncs"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

'---------------------------------------------------------------------------------------
' Module    : IReportingHandler_AgencyFuncs
' Author    : Dmitry Gorelenkov
' Date      : 08.11.2013
' Changed   : 08.11.2013
' Purpose   : Interface for extra functions of any Agency
' Requires  : clsMyCollection
' Info      : Maybe low quality code :/
'---------------------------------------------------------------------------------------


Public Function getReportingData() As clsReportingData

End Function
